name: skawa_components
version: 1.5.2
authors:
  - Harsányi Tamás (valakis) <tams.harsnyi@google.com>
  - Szepesházi András <szepeshazi@gmail.com>
  - Varga-Hali Daniel <https://github.com/daniel-v>
  - Farmasi Bulcsú <https://github.com/BulcsuFarmasi>
description:
  Additional components for AngularDart based on Material Design principles. These reusable components are not part of the official  Material Components library.
homepage: https://github.com/skawa-universe/skawa_components

environment:
  sdk: '>=2.9.0 <3.0.0'

dependencies:
  angular: ^7.0.2
  angular_components: 
    git:
      url: https://github.com/angulardart-community/angular_components.git
      ref: compatible
  sass_builder:  
    git:
      url: https://github.com/meynety/sass_builder.git # Custom because of angular_components
  markdown: ^3.0.0
  js: ^0.6.1+1
  intl: ^0.16.0
  diff_match_patch: ^0.3.0
  meta: ^1.2.2

dev_dependencies:
  html_unescape: ^1.0.1+2
  mockito: ^4.0.0
  test: ^1.6.2
  angular_test: ^3.0.0
  pageloader:
    git:
      url: https://github.com/skawa-universe/pageloader.git
      ref: analyzer-40
  build_config: ^1.0.0
  build_test: ^1.0.0
  build_runner: ^1.7.0
  build_web_compilers: ^2.0.0
