name: skawa_material_components
version: 1.5.1
authors:
  - Hars치nyi Tam치s (valakis) <tams.harsnyi@google.com>
  - Szepesh치zi Andr치s <szepeshazi@gmail.com>
  - Varga-Hali Daniel <https://github.com/daniel-v>
description:
  Additional Material Design components for AngularDart. Complements the official `angular_components` package.
homepage: https://github.com/skawa-universe/skawa_components

environment:
  sdk: '>=2.9.0 <3.0.0'

dependencies:
  angular: ^7.0.2
  angular_components: 
    git:
      url: https://github.com/angulardart-community/angular_components.git
      ref: compatible
  quiver: ^3.1.0
  sass_builder:  
    git:
      url: https://github.com/meynety/sass_builder.git # Custom because of angular_components
  intl: ^0.16.0

dev_dependencies:
  test: ^1.6.2
  angular_test: ^3.0.0
  pageloader:
    git:
      url: https://github.com/skawa-universe/pageloader.git
      ref: analyzer-40
  build_config: ^0.4.1+1
  build_test: ^1.0.0
  build_runner: ^1.7.0
  build_web_compilers: ^2.0.0
